apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: checkurl
  name: checkurl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkurl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: checkurl
    spec:
      containers:
      - image: meghjangi/checkurl:v2
        name: checkurl
        ports:
        - containerPort: 8000
        resources: {}
status: {}
