apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-10-25T16:29:15Z"
  generation: 2
  labels:
    app: checkurl
  name: checkurl
  namespace: default
  resourceVersion: "55909"
  uid: 40508e61-7f61-4264-88ef-ebf846ae0c96
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: checkurl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: checkurl
    spec:
      containers:
      - image: meghjangi/checkurl:v2
        imagePullPolicy: Always
        name: checkurl
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-10-25T16:30:02Z"
    lastUpdateTime: "2022-10-25T16:30:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-10-25T16:29:15Z"
    lastUpdateTime: "2022-10-26T04:54:49Z"
    message: ReplicaSet "checkurl-66d7b45548" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1